### ISSUE TITLE
Adding include template for images

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#10]
Currently generated as
```
<figure class="figure"><img src="{{ site.baseurl }}/Images/modules/cmn/grace-300.png" class="img-responsive"><figcaption class="figure-caption">Figure 2. Grace notes</figcaption>
</figure>
```
One question to address is figure numbering. Do we want to keep it?

**Comment by kepper** [comment]
as PDF is not our main output (anymore), I'm happy to drop image numbering. The images directory should be cleaned up, yes. But I also agree that this can happen at a later point…

**Comment by lpugin** [comment]
So if we want to postpone it then we need to have an distinct image set for each version. I'll take care of this. It does actually not matter for the template, which will be
```
{% include figure img="modules/cmn/grace-300.png" caption="Grace notes" %}
```
OK?

**Comment by lpugin** [comment]
We need to remove in the XSLT the "/Images" we have in the path in order to have distinct version of the images for each version. So the result should be as above and not `img="Images/modules/cmn/grace-300.png" `

**Comment by lpugin** [comment]
I fixed this one. I made a few changes directly in the canonicalized3.0.0.xml. However, because this is only to migrate the guidelines it will not cause any problem in the future. @bwbohl just make sure you use that file too.
