### ISSUE TITLE
Add overview of available modules to guidelines?

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/guidelines#101]
There is an overview for elements, attributes etc., but not for the available modules. Maybe this would be good to have, as every element description is pointing to a certain module and attributes and models and the like can be sorted "by module". 

Additionally, there could/should be a link from both locations to the module overview descriptions.

**Comment by musicEnfanthen** [comment]
Modules are here: https://github.com/music-encoding/music-encoding/tree/develop/source/modules

**Comment by kepper** [comment]
I was thinking about adding that to the new chapter 1 of the Guidelines, but that might be too hidden…

**Comment by musicEnfanthen** [comment]
Yes, too hidden. May be as a separate entry on the right panel next to `Elements`, `Atttribute Classes` etc..

**Comment by kepper** [comment]
And from there on? Open a page with the full list of modules. Each of those could be a link that points to another overview page which gives a brief description at the top (probably just the `//moduleSpec/desc`), and then lists all elements, model / att classes etc. from that module. Right?

**Comment by musicEnfanthen** [comment]
Yes, analogue to the Elements, Attributes etc. pages

**Comment by musicEnfanthen** [comment]
Closing since modules are now integrated into the guidelines dev version.
