### ISSUE TITLE
Filename CON not allowed on Windows

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/guidelines#105]
As it turns out, `CON `is a reserved name on Windows systems, see the following two links:

- https://stackoverflow.com/a/51523161
- https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#naming-conventions

This affects 3 files in the v4 guidelines and 1 in v3 named `con.txt` (what is a brilliant file name, by the way):

- [_includes/v4/desc/att.syl.log](https://github.com/music-encoding/guidelines/blob/master/_includes/v4/desc/att.syl.log/con.txt)
- [_includes/v4/desc/att.ncform](https://github.com/music-encoding/guidelines/blob/master/_includes/v4/desc/att.ncform/con.txt)
- [_includes/v4/desc/att.nc.vis](https://github.com/music-encoding/guidelines/blob/master/_includes/v4/desc/att.nc.vis/con.txt)
- [_includes/v3/desc/att.syl.log](https://github.com/music-encoding/guidelines/blob/master/_includes/v3/desc/att.syl.log/con.txt)

When cloning the guidelines repo, Windows deletes the files immediately and prevents the repo from being checked out properly. Additionally, the local compilation of the guidelines fails on Windows when arriving at [08-lyricsperfdir/02-lyricsdesc/01-lyricssyl.md](https://github.com/music-encoding/guidelines/blob/0a2524c40bd2f9ac71a8433b25868363c393b62f/_guidelines-v4/08-lyricsperfdir/02-lyricsdesc/01-lyricssyl.md) because this file calls the `_includes/v4/desc/att.syl.log` file mentioned above that is then deleted by Windows.

Tried to restore the automatically deleted files (via GIT), replace or rename the file (via IDE) or rewrite the file. It is not possible. As a temporal (and dirty) workaround, the only way to get the local build running at least, was to delete the call to `_includes/v4/desc/att.syl.log` in the `01-lyricssyl.md`.

Does anyone see a solution to that? Renaming the file might involve renaming the (different) `con` attributes, which doesn't seem to be the best idea.

**Comment by ahankinson** [comment]
Thanks, @musicEnfanthen ! That is indeed a frustrating bug.

I've tried to find a way around this but it doesn't seem like there's any real solution. Changing the `@con` would be a backwards-incompatible change, so that wouldn't be good. 

Maybe we can have a change in the XSLT parser that will handle `con.txt` differently?

**Comment by musicEnfanthen** [comment]
Thanks for looking into this!

Renaming the con.txt to something like att-con.txt would not be feasable, I guess? But it is introducing inconsistency if not applied to all those attribute related .txt files

**Comment by ahankinson** [comment]
The name of the files is managed by the XSLT that generates the markdown files from the schema. Any renaming should happen in the XSLT, and then (🤞) it will all still magically work.

**Comment by bwbohl** [comment]
am I right to assume, that the include files consequently have to be regenerated? Currently serving the guidelines locally fails due to _desc files not being found!

**Comment by craigsapp** [comment]
https://www.youtube.com/watch?v=bC6tngl0PTI

**Comment by musicEnfanthen** [comment]
Great find, thanks 👍
