### ISSUE TITLE
Child element description

### ISSUE THREAD

**Issue by irmlindcapelle** [music-encoding/guidelines#106]
In the guidelines the description of the child elements is not correct: all child elements have the text of the mother element and not their own text

**Comment by ahankinson** [comment]
Could you please post a link to an example?

**Comment by kepper** [comment]
On https://music-encoding.org/guidelines/v4/elements/manifestation.html, when you look at the "may contain" facet in "by class" mode, you will get the content of //manifestation/desc, not of the descs of those direct child elements. My fault :-)

**Comment by irmlindcapelle** [comment]
this mistake is also to find in the description of the elements for example under model.textPhraseLike.limited (and other "models"); see for example <decoDescr> Element
https://music-encoding.org/guidelines/v4/elements/decodesc.html
