### ISSUE TITLE
Chapter 04: Chord element not adressed in Guidelines

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/guidelines#108]
Chapter 4 of the Guidelines has a section [4.2.4. Notes, Chords and Rests in CMN](https://music-encoding.org/guidelines/v4/content/cmn.html#cmnNotesChords)

Subchapters are only adressing Notes & Rests, Chords are not adressed separately. Although the handling of chords can be easily understood by experienced users using the examples in the notes section, it could be difficult for beginners to find (or understand) chords.

Related to #107 ?

**Comment by lpugin** [comment]
Fully agree. Things that should probably be documented are:
* encoding of duration on chords: do we recommend to put a duration on the chord element?
* chords with notes with different durations: do we recommend to put the longest duration on the chord element?
* use of dots and dots.ges when some notes are missing a dot
* placement of artic (within chord or within notes)
