### ISSUE TITLE
Issue with camel-cased links in the latest version

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#11]
In the dev (v4) version some links are broken because of camel-cased names. They should be lower-cased.

See :
https://music-encoding.github.io/guidelines/v4/attribute-classes.html
pointing to:
https://music-encoding.github.io/guidelines/v4/attribute-classes/att.beamedWith.html
instead of:
https://music-encoding.github.io/guidelines/v4/attribute-classes/att.beamedwith.html

**Comment by bwbohl** [comment]
seems to me the links provided above are correct now

**Comment by lpugin** [comment]
OK, thanks. I am waiting to see once the XSLT is applied again, but I need some input from @ahankinson or @kepper for this. How can we trigger the XSLT?

**Comment by ahankinson** [comment]
I was able to run it with saxon on the command line. 

```
$> brew install saxon
$> cd tools
$> saxon -xsl:extractGuidelines.xsl canonicalized3.0.0.xml
```

Does that work?

**Comment by lpugin** [comment]
It does generates the guidelines. However, everything goes in a subdirectory ./tools/v3 and not at its right place. I copy them by hand but we should change this.
* ./tools/v3/desc should go into ./_includes/v3/desc
* ./tools/v3/examples should go into ./_includes/v3/examples
* ./tools/v3/guidelines should go into ./_guidelines-v3/
* all the rest to ./v3

There is one problem with ./tools/v3/guidelines.md that is missing a `---` header end. It is 
```
---
layout: sidebar
sidebar: s1
title: "Guidelines"
version: "v3"
<div>
   <h3 class="widget-title">Table of Contents</h3>
```
instead of 
```
---
layout: sidebar
sidebar: s1
title: "Guidelines"
version: "v3"
---
<div>
   <h3 class="widget-title">Table of Contents</h3>
```

**Comment by lpugin** [comment]
The link issue is not quite solved. See in
http://music-encoding.org/guidelines/v3/model-classes
The link points to
http://music-encoding.org/guidelines/v3/model-classes/model.chordpart.html
But the file is still
http://music-encoding.org/guidelines/v3/model-classes/model.chordpart.html
So the problem seems to be the opposite as the issue described in the first place. I would suggest to have all files and all links lower-cased. OK?

**Comment by lpugin** [comment]
OK, this is now be fixed. (I had to remove the entire directory and put it back in order to have the pages updated.)

**Comment by lpugin** [comment]
All links should be good except from the ones in the remarks. See http://music-encoding.org/guidelines/dev/elements/userestrict.html. Not sure how to fix them in the XSLT.
