### ISSUE TITLE
layout of specs broken

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#110]
Some commit that happened in the past 12 hours must have broken the layout of the specs:

https://music-encoding.org/guidelines/v4/elements/manifestation.html#attributes

The CSS is generally available (it would be much worse otherwise), but the current state is unusable. I suspect that a classname got lost, on which parts of the layout rely, but this is just a first assumption. 

I can look into this, but not before or during the first session today at MEC…

**Comment by lpugin** [comment]
Just to make it clear: the CSS of the website is used for the guidelines, so changes quite likely occurred here https://github.com/music-encoding/music-encoding.github.io

**Comment by lpugin** [comment]
Fixed with https://github.com/music-encoding/music-encoding.github.io/pull/91
