### ISSUE TITLE
branching model

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/guidelines#13]
Dear all,

I just was about to start working on some guidelines issues and stumbled over the current branch situation. Apparently "master" is where the development happens and the other branches "develop", "feature-travis" and "feature-gemfile" are somewhat stale and behind at least by 85 commits.
Nevertheless the naming scheme of the branches as the presence of both "master" and "develop" suggest a "gitflow" approach.

Can we agree on gitflow? I.e. the "master" branch being for tagged releases (maybe only PR-able by others) "develop" as main area for (as the name suggests ;-) development and use feature, release and hot fix branches as e.g. introduced by Vincent Driessen in his post «A successful Git branching model» at http://nvie.com/posts/a-successful-git-branching-model/?

I'd very much appreciate that!

Of course this should be documented in the README's section on contributing, but that's another issue.

**Comment by ahankinson** [comment]
We could set the master branch to be 'protected' to enforce this, if it's something we can agree on.

**Comment by bwbohl** [comment]
That sounds reasonable to me and is what I  meant.
Basically that would also require a gitflow-ish use of branches as one could not directly modify it.

**Comment by lpugin** [comment]
Thanks for willing to contribute, but at this stage the conversion from the MEI/TEI guidelines is not finished. So a first highly desirable contribution would be to fix the remaining issues listed for this repository...

**Comment by lpugin** [comment]
The plan it to have only "master". The branch itself will have different versions of the guidelines, including "dev" corresponding to the "develop" branch of MEI. When we make a release, "dev" is copied to the corresponding version number, and remains for further modifications. For example, when we will make the 4.0 release of MEI, "dev" guidelines will be copied as a new "v4". When 4.1 comes out, "dev" replaces "v4". This means that we will have online one version of the guidelines for each major release, plus the development version.
