### ISSUE TITLE
Encoding pedal lines

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#138]
I'd like to improve and expand the pedal section in chapter 04. But I'm not quite shure how to encode piano pedal lines. AFAICS there are different possibilities (refers to https://github.com/music-encoding/music-encoding/issues/305). 
Should the recommended (the simplest) way be `<pedal tstamp="1" tstamp2="4" form="line" />`?

**Comment by musicEnfanthen** [comment]
@rettinghaus Is this now clearer since https://github.com/music-encoding/music-encoding/pull/1003 has been merged? Can the issue here be closed then?
