### ISSUE TITLE
Styling of figure captions

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/guidelines#154]
It would be nice to have a styling of figure captions that distinguishes them from the normal textflow

**Comment by rettinghaus** [comment]
Yes! How about *small* and *italic*?

**Comment by bwbohl** [comment]
any chance of automatically numbering the figures (images and code examples)?
and providing the link to the example-file?

**Comment by musicEnfanthen** [comment]
@bwbohl Can this one be closed?

**Comment by musicEnfanthen** [comment]
I will check. Thanks
