### ISSUE TITLE
multirest.md block description

### ISSUE THREAD

**Issue by davidrizo** [music-encoding/guidelines#163]
Currently the block description of [multi-measure rests](https://github.com/music-encoding/guidelines/blob/master/v4/elements/multirest.md#) refers to a page of an unknown source: "(Read, p.104)":

> block When the block attribute is used, combinations of the 1, 2, and 4 measure rest forms (Read, p. 104) should be rendered instead of the modern form or an alternative symbol.

**Comment by craigsapp** [comment]
This is the citation:

Garner Read. Music Notation: A Handbook of Modern Practice. Taplinger Pulblishing Company:; 1979.

https://www.amazon.com/Music-Notation-Crescendo-Book-Gardner/dp/0800854535

**Comment by rettinghaus** [comment]
This is not in the guidelines but the schema. 
Fixed here: https://github.com/music-encoding/music-encoding/pull/626

**Comment by bwbohl** [comment]
The Name is »Gardner Read«

**Comment by bwbohl** [comment]
Maybe the Guidelines should retain the reference to Gardner Read? Or alternatively provide a rendered example of the alternatives

**Comment by rettinghaus** [comment]
Sorry, but the guidelines show the difference.

**Comment by rettinghaus** [comment]
@bwbohl and still the wrong repo.

**Comment by rettinghaus** [comment]
NB: Some weeks ago I started this discussion: https://github.com/music-encoding/music-encoding/issues/653

**Comment by rettinghaus** [comment]
Was fixed in 2020 and a follow-up ticket was created.
