### ISSUE TITLE
Guidelines miss styling in Safari

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#164]
Lately the Guidelines miss all the CSS stuff in Safari. Please confirm.

**Comment by kepper** [comment]
Nope, all looking good for me, even with an emptied cache. Could you double-check on your end?

**Comment by rettinghaus** [comment]
Mysterious! Now it's working again for me …

**Comment by kepper** [comment]
it just heard it's master's voice ;-) If all issues were to be resolved that easily…
