### ISSUE TITLE
Misleading content model info

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/guidelines#172]
The "May Contain" info for elements whose content model is defined as
```
<content>
  <rng:ref name="macro.struc-unstrucContent" />
</content>
```
erroneously displays "may not have child elements".  In fact, macro.stuc-unstrucContent allows either 1) a strict model `(head*, p*)` or 2) a mixed-content model made up of members of model.textPhraseLike.limited and text.

**Comment by bwbohl** [comment]
@pe-ro could you just add one link to an example?

**Comment by rettinghaus** [comment]
e.g. https://music-encoding.org/guidelines/v4/elements/layout.html#mayContain
