### ISSUE TITLE
Chapter 05 (dev): MEI examples to be rendered in Verovio are not shown

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/guidelines#175]
For some reason, in the [development version of the guidelines](https://music-encoding.org/guidelines/dev/content/mensural.html), the MEI examples that I included in the "mei/dev/" folder are not showing. Just the first example is shown, the "notes_rests.mei", but all following are not displayed (neither the MEI encoding nor the Verovio rendition of it). In my local machine, all examples do render (see [link](https://www.icloud.com/iclouddrive/0p4nEPXlD9ByY4thjrhFVmaXQ#module%5Fguidelines%5Fv5)). 

I don't know why this is happening. I have cloned this exact same repo and while the examples are displayed on my local machine they are not displayed on the website.

**Comment by martha-thomae** [comment]
Also, the font for the examples is different, the one shown on my local machine makes the MEI encoding easier to read (see the text in bold and the different colors).

**Comment by kepper** [comment]
Without havind had a closer look at the problem itself: The CSS for the Guidelines is provided in the https://github.com/music-encoding/music-encoding.github.io repo, which admittedly is a nightmare to debug and should be changed asap. This probably doesn't explain why examples don't show up, but it could explain why things look different, assuming that you have a local copy of that other repo running locally…

**Comment by lpugin** [comment]
(@kepper I feel every day worse and worse about the guidelines setup which was my proposal. Please get rid of it as soon as you can.)

I'll have a look at the Verovio stuff. We can go back to static images if this is preferred.

**Comment by martha-thomae** [comment]
@kepper, that could be the case for the fonts since I do have the website's GitHub also cloned (well, a fork of it, but same thing).

@lpugin, I love the Verovio stuff! I certainly do prefer this over static images because it is good to see that the encodings can actually be rendered somewhere (here, Verovio). It would also be good to have the same thing as the tutorials (or in the Verovio website) where you can click on "show full encoding" as well.

**Comment by kepper** [comment]
@lpugin, no worries. You had good arguments, which apparently convinced us all at some point ;-)  But after a couple of years of operating this setup, we have a better picture now, and see that the benefits come at a cost we didn't foresee back then. We'll change that situation now, but it's already clear that every setup will have it's own issues…

**Comment by lpugin** [comment]
It should be fixed. The problem came from the capital letters in the file names. GitHub servers make the distinction be upper and lower case. Another reason to move away from the current setup ;-) Until then we need to use always lower case filenames.

**Comment by martha-thomae** [comment]
Thank you, Laurent!

**Comment by bwbohl** [comment]
> It should be fixed. The problem came from the capital letters in the file names. GitHub servers make the distinction be upper and lower case. Another reason to move away from the current setup ;-) Until then we need to use always lower case filenames.

could you please documet somewhere which files have to stick to lowercase naming scheme?
