### ISSUE TITLE
Update Verovio version

### ISSUE THREAD

**Issue by martha-thomae** [music-encoding/guidelines#176]
Switch to develop version for MEI examples to be rendered correctly (including: [implicit mensuration example](https://github.com/music-encoding/guidelines/blob/master/mei/dev/implicit-mensuration.mei)).

This was pointed out on https://github.com/rism-ch/verovio/issues/1489#issuecomment-640763107

**Comment by bwbohl** [comment]
@lpugin could you handle this?

**Comment by lpugin** [comment]
378f6e3d018c92175d05614d954e88920b8757dc

**Comment by martha-thomae** [comment]
Thank you!
