### ISSUE TITLE
tables in markdown

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/guidelines#18]
the current files have a html table in the markdown files is this a workaround that should be fixed to output something else (more markdownish) or do we stick to it?

**Comment by bwbohl** [comment]
from my perspective we should get rid of all non markdown stuff, right? The idea is to simplify things that also means to stick to but one encoding scheme and not mixing them.

**Comment by lpugin** [comment]
Yes, absolutely! Anything you can improve there is welcome

**Comment by bwbohl** [comment]
ok I gather there are some problems in doing what the element-spec table should look like in markdown. Markdown doesn't support block-level markup in tables.So we might have to stick with the HTML or come up with some other structure…

**Comment by lpugin** [comment]
Do you have an example? Can we simplify it? Otherwise we  can keep the HTML for now

**Comment by bwbohl** [comment]
well markdown can't handle tables in tables as we have them e.g. with the attributes or multiple paragraphs in the same table cell are likewise problematic…

all markdown can handle is set-level things like bold italic etc. `inline code` 

|col1|col2|
| ------------- |-------------|
|bold |italic|
trying a paragraph in the first cell

and a second| doesn't work

though

**Comment by lpugin** [comment]
OK, let's leave it for now. What about the lists? Once we have this I would like to cleanup the MD for version 3.0 and generate the guidelines for version 4.0 (I need the canonicalized version for this). We can then cleanup the XSLT and remove the TEI parts from the source. @pe-ro ? OK with this?

**Comment by bwbohl** [comment]
so the canonicalised v4 would be the current dev status from the music-encoding repo? as there is not tagged release yet?

**Comment by lpugin** [comment]
Yes, this would be it. No tag yet, but maybe we should have one just for this? It is not the release, but the switch from TEI to MD, so definitely quite a big switch.

Take your time, I also have other things this afternoon.

**Comment by pe-ro** [comment]
Sorry if this is a stupid question -- Where / how can I view the current state of this in my browser?

**Comment by ahankinson** [comment]
https://music-encoding.github.io/guidelines

**Comment by pe-ro** [comment]
Thanks

**Comment by lpugin** [comment]
(some?) tables are not in converted to html anymore. (see https://github.com/music-encoding/guidelines/blob/master/_guidelines-dev/08-cmnornaments/02-cmnornamentsmordents.md)  I cannot find the modification in the XSLT that changed this. @bwbohl any idea?

**Comment by lpugin** [comment]
Found it
