### ISSUE TITLE
Refer to TEI Guidelines

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#189]
When MEI elements come directly from TEI (or are modelled after TEI) it would be good to refer to the corresponding site from the TEI Guidelines, or at least recommend to check the description and examples over there.

**Comment by kepper** [comment]
I had the very same idea looking at the guidelines today, yes. I'm afraid this needs to be done manually (at least to some degree), but it would surely be a helpful improvement. There are also references to other encoding schemes which should be treated likewise…

**Comment by kepper** [comment]
Doing an XPath search for `//elementSpec[.//remarks//text()[contains(.,' TEI') or contains(.,' EAD') or contains(.,' modelled')]]/@ident` reveals **176** elements that probably need to get a reference to another standard. 
**118** of those use the standard phrase `//elementSpec[.//remarks//text()[contains(.,'This element is modelled on an element in the Text Encoding Initiative (TEI) standard.')]]/@ident`. For them, it's probably possible to set a reference  link automatically. I'll see what I can do about it…

**Comment by rettinghaus** [comment]
@kepper I was looking into that and was wondering if we need a link to the description of the element itself or if it would be enough to link to the TEI Guidelines. 
If I'm not mistaken they always share the name with the respective TEI element, so an automatic link could be `https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-*ELEMENTNAME*.html`.

**Comment by kepper** [comment]
yes, that's what I thought. We can use doc-available to check whether the name is actually the same  and the link can be inserted automatically, or if we need to add this manually. Shouldn't be too hard to do, I'm just not sure I'll find the time before the afternoon meeting ;-)

**Comment by bwbohl** [comment]
2021-06-24 ODD Thursday:

Considering this is not done yet, I just want to point to other standards that could/should be treated equally then. Especially with the TEI (and maybe all the standards) which version of the standard did MEI refer to when the element was introduced, as definitions of the elements might have changed (e.g. tei:lb was line break and could mark line endings or beginnings, today it's line beginning exclusively.

**Comment by musicEnfanthen** [comment]
Closed by https://github.com/music-encoding/music-encoding/pull/1027
