### ISSUE TITLE
version folders

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/guidelines#193]
Comparing this repo to https://github.com/music-encoding/schema shoudn't the names of the containing version-folder match? Here we have v3, v4, dev while at the schema repo we have more verbose versioning, e.g. 3.0.0, 4.0.0, 4.0.1.

Of course this brings up the question, whether pre-patch-revisions should be kept at all, e.g. schema version 4.0.0 vs 4.0.1!? If so probably the guidelines should also be kept. Consequently folder-names in this repo should be the same as in the schema repo.

**Comment by lpugin** [comment]
As far as I remember it was a decision not to have distinct versions of the guidelines for even patch and minor revisions (hence v3, v4). This is OK for me. If somebody wants to see the guidelines for 4.0.0 they can always checkout the repo and rebuild them.

**Comment by bwbohl** [comment]
and for the latest develop-branch version it would be dev, right? what about the version number for dev in the `@meiversion`? (see also https://github.com/music-encoding/music-encoding/pull/740)

**Comment by kepper** [comment]
If I remember correctly, this decision was based on the fact that having multiple versions side by side was rather complex in the old setup. However, I'm with @lpugin that this should be sufficient – as by definition there are no breaking changes (besides bug fixes), and so things should be mostly compatible. However, I would suggest that from here on out we'll preserve the PDF versions of every release. As they're supposed to get a DOI, that will happen anyway, and we just need to make them accessible on our website…
