### ISSUE TITLE
guidelines dev is missing index.html

### ISSUE THREAD

**Issue by bwbohl** [music-encoding/guidelines#194]
see also https://github.com/music-encoding/music-encoding.github.io/issues/195

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="0;url=/guidelines/dev/content" />
    </head>
    <body>
    </body>
</html>
```

should do the job

**Comment by lpugin** [comment]
Should be:
```html
<meta http-equiv="refresh" content="0;url=./content" />
```

**Comment by bwbohl** [comment]
file should be generated by the CI Action, right?

**Comment by lpugin** [comment]
> Generally the file should be generated by the CI Action, right? 

No, by the XSLT in my opinion.

> How do we proceed with the current dev in this repo, add it manually?

You can. But I think it should be possible to fix this and merge the PR.

**Comment by bwbohl** [comment]
@kepper do you prefer to put this in a index.html file in the source that will be copied to the destination by the XSLT or add is as template that will be called in a separate <xsl:result-ducument> instruction?
