### ISSUE TITLE
Wrong menu for the devlopment version

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#195]
It seems that the development version of the guidelines pulls the v4 menu instead of the dev one. As a result, the notification is not showing up.

**Comment by kepper** [comment]
probably because the version number in the specs still reads 4.0.1, but I'll have a look – I've spotted a number of other inconsitencies anyway…

**Comment by bwbohl** [comment]
how is the menu being pulled? I issued a PR (https://github.com/music-encoding/music-encoding/pull/747) changing the dev version to 4.0.1-dev maybe that fixes it? Or we could pass the branch name of the build, i.e. dev at the moment.

**Comment by kepper** [comment]
Hi @bwbohl, thanks for the PR. I'm afraid there is some logic involved that needs to be adjusted in the XSLT. I'll happily do that today, but no time before the afternoon…
