### ISSUE TITLE
Links to TEI guidelines still broken

### ISSUE THREAD

**Issue by musicEnfanthen** [music-encoding/guidelines#196]
Related to music-encoding/music-encoding#743 

In the [latest dev version](https://github.com/music-encoding/music-encoding/commit/29ce50c4c4eb0633cb85e1bf7349c12b4d7b4a66), the links to the TEI guidelines in [Chapter 14.4 SVG](https://music-encoding.org/guidelines/dev/content/integration.html#svg) are still broken because they are resolved to:

`https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-moduleRef.html.html`

Is it possible that the $text variable in the [guidelines.xsl]( https://github.com/music-encoding/music-encoding/pull/743/files#diff-d5c8d83e02bff851103c33f807f94be0abbfd287047181bdedf1b4706cf743a2R132-R134) already inlcudes the `.html`, or where does the double `html` come from?

**Comment by bwbohl** [comment]
@kepper could you have a look?

**Comment by kepper** [comment]
will do

**Comment by kepper** [comment]
As I used the same class name for external TEI links, and the treatment for links for the website was based on those css classes, I've adjusted the link as I have to for our internal links. Thanks for spotting this 👍

**Comment by musicEnfanthen** [comment]
Great. Would it work then with `doc-available` again?

**Comment by kepper** [comment]
Probably not – that check is done at an earlier stage, before the duplicate `.html` got introduced, so that the fix above doesn't affect it…

**Comment by musicEnfanthen** [comment]
Ah, ok. Thanks for fixing it 👍
