### ISSUE TITLE
Guidelines text is cramped

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/guidelines#2]
There's a lot of white space in the guidelines docs. I propose changing it to fill more of the screen. 

Also, the striped 'table' of attributes changes background on hover, which is strange.

I can fix this if that's ok?

**Comment by kepper** [comment]
I only started work on the elements, but none of the other objects. I agree on the table, just haven't had the time to change it yet. I'm happy with you stepping in (why shouldn't I?), otherwise I'll get back into it next week…

**Comment by bwbohl** [comment]
is #19 fixing what you were complaining about, at lest in parts?
