### ISSUE TITLE
Typo in v.4 Guidelines Ch. 3

### ISSUE THREAD

**Issue by annakijas1** [music-encoding/guidelines#201]
This heading in [section 3.3.2](https://music-encoding.org/guidelines/v4/content/metadata.html#headerrespstatement) has a typo. It reads: "Responsility Attribution"
It should read "Responsibility Attribution"

**Comment by rettinghaus** [comment]
Thanks for reporting.
fixed with 5139d7d78e0f3183f0f799bd5ffc6dc9e140338a
