### ISSUE TITLE
Namespaces in examples

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#22]
Do we really want / need to have these namespaces in all examples?
```xml
xmlns="http://www.tei-c.org/ns/Examples" xmlns:rng="http://relaxng.org/ns/structure/1.0" xmlns:sch="http://purl.oclc.org/dsdl/schematron" 
```

**Comment by bwbohl** [comment]
no, we definitely don't want them!
I'm still working on this in the XSLT though…

**Comment by lpugin** [comment]
Don't spend too much time on fixing the XSLT. I can drop them with search an replace. The examples will not extracted with it in the future, only the tag library.
