### ISSUE TITLE
specDesc template not requiring version

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#3]
We should change the specDesc template calls from
```
{% include specDesc.html version=page.version elem="mei" atts="" %} 
```
to just
```
{% include specDesc.html elem="mei" atts="" %} 
```

**Comment by lpugin** [comment]
Actually for elements to
```
{% include desc elem="mei" %}
```
and for attributes to
```
{% include desc atts="att.meiversion/meiversion" %}
```

**Comment by lpugin** [comment]
Once this is done we can remove the `_include/specDesc.html` template

**Comment by bwbohl** [comment]
If I see this correctly this has already been implemented?

**Comment by lpugin** [comment]
Yes. What needs to be changed is the XSLT that produces the markdown. @kepper, can you help @bwbohl to change this?

**Comment by bwbohl** [comment]
already spotted the line in the XSLT

**Comment by bwbohl** [comment]
it says
https://github.com/music-encoding/guidelines/blob/ae76672e19ba7057e07d02cf002d340289d5ead2/tools/extractGuidelines.xsl#L1025 

and
https://github.com/music-encoding/guidelines/blob/ae76672e19ba7057e07d02cf002d340289d5ead2/tools/extractGuidelines.xsl#L1059

output for e.g.

```xml
<specDesc key="mei"></specDesc>
```

if the corresponding tie-element with `@ident` equal to `specDesc/@key` can be retrieved would consequently be 
```md
{% include desc elem="mei" %}
```

or for e.g.

```xml
<specDesc atts="meiversion" key="mei"></specDesc>
```
if corresponding `tei:attDef` with `@ident`equal to a token of the above's `@atts` would be

```md
{% include desc atts="<xsl:value-of select="string-join($refs,' ')"/>" %}
```

If a element reference cannot be resolved it aborts, if an attDef cannot be retrieved it outputs a corresponding message

**Comment by bwbohl** [comment]
so you can consider this ticket closed
