### ISSUE TITLE
Remove 'xinclude' Namespace in examples

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/guidelines#40]
As a consequence of the migration the xinclude namespace now seems to be added to many of the examples. This should be removed.

See, for example: 

https://github.com/music-encoding/guidelines/blob/07501b123480dd0a5f621b885eb6b6dd9e5b7167/_includes/dev/examples/cmn/cmn-sample099.xml

**Comment by lpugin** [comment]
Could you double check the status in the master branch?

**Comment by ahankinson** [comment]
Do you mean the v3 folder? It's not there. What's the difference?

**Comment by lpugin** [comment]
No, I mean the same file in the master branch: https://github.com/music-encoding/guidelines/blob/master/_includes/dev/examples/cmn/cmn-sample099.xml

We actually do not use develop. We should probably drop it for now, and just have one whenever we are going through a development phase that needs one.
