### ISSUE TITLE
example glyphs missing in text

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#41]
There are several glyphs in the guidelines text missing now, e.g. see MEI_Guidelines_v3.0.0.pdf p. 160 and p. 168.
How should that be addressed?

**Comment by lpugin** [comment]
Some more information about the current status:

![image](https://user-images.githubusercontent.com/689412/41853321-cfaa4d66-788d-11e8-8b54-8749eebaf713.png)

http://music-encoding.org/guidelines/dev/content/cmnornaments.html#cmnOrnamentsMordents

https://github.com/music-encoding/guidelines/blob/master/_guidelines-dev/08-cmnornaments/02-cmnornamentsmordents.md

**Comment by ahankinson** [comment]
Is there a SMuFL-compatible webfont available we can use? Can we encode the SMuFL glyph code in the documentation with a CSS wrapper, e.g.,

```
<span class="smufl">\U+0000</span>
```

?

**Comment by lpugin** [comment]
What about using the edirom smufl browser? Something like:

![SMuFL-E56D](http://edirom.de/smufl-browser/E56D.png)

**Comment by ahankinson** [comment]
The downside to doing that would be relying on an external service for our documentation. If the smufl-browser goes away, or changes its URLs, we wouldn't know.

**Comment by lpugin** [comment]
We can use the woff BravuraText, but it is 1.2Mb

**Comment by kepper** [comment]
What if we just include some images? That's not very flexible, but small…

**Comment by rettinghaus** [comment]
@kepper where to get them?

**Comment by kepper** [comment]
Not sure if I get the question. I would just take a screenshot from the smufl browser (or anything else) and upload that to our site. The other possible question would have been how to load that image in this particular place, and admittedly, I haven't looked into that yet.

**Comment by lpugin** [comment]
http://edirom.de/smufl-browser/E56D.png

**Comment by rettinghaus** [comment]
Actually I found some of them in the guidelines (well hidden):
https://github.com/music-encoding/guidelines/blob/master/images/dev/modules/cmnOrnaments/turn.png

Proposal: gather the musical glyphs in a single folder.

**Comment by ahankinson** [comment]
What about a `smufl` include that takes the SMuFL codepoint and loads the PNG?

```
{include smufl code="E65D" }
```

**Comment by kepper** [comment]
First, I was worried that the situation originally referred to was already an include from our /desc folder, but actually, it's not (it lives directly within https://github.com/music-encoding/guidelines/blob/master/_guidelines-v3/08-cmnornaments/02-cmnornamentsmordents.md). I think Andrew's proposal is the best way to go then. But we still need to decide if we want to rely on the smufl browser to retrieve the image, or if we want to cache them locally. I can see arguments for both…

**Comment by ahankinson** [comment]
I say let someone else do the work. :) 

Seriously, though -- I think we can go with the SMuFL browser until such time as it doesn't exist, and then explore our options, which could range from storing our own to using a webfont. It should be possible to do both if all we are doing is storing the SMuFL codepoint.

**Comment by lpugin** [comment]
Since I proposed it I am happy to take the decision: yes.

**Comment by ahankinson** [comment]
OK -- I've got it almost ready to go in a PR.

**Comment by rettinghaus** [comment]
This is working now.
