### ISSUE TITLE
use Jekyll-Scholar

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#58]
For bibliographic references within the guidelines we should store these in a BibTeX file and make use of https://github.com/inukshuk/jekyll-scholar

**Comment by musicEnfanthen** [comment]
Agree with @ahankinson. Jekyll Scholar looks pretty promising but seems to have a problem with Github Pages workflow according to this: [https://github.com/inukshuk/jekyll-scholar#github-pages](https://github.com/inukshuk/jekyll-scholar#github-pages)

What would/should bibliographic references in the guidelines look like? Do you have an example?

**Comment by rettinghaus** [comment]
No, @musicEnfanthen, didn't use it so far. Just thought, as you, that it looks promising. 

Problem is, that in the guidelines all bibliographic references are scattered and not consistent in style. After you did the job on the main pages, I thought you may want to have a look at it. But will do too, as soon as I'll get to it.

**Comment by musicEnfanthen** [comment]
Thanks. I definitely will have a closer look at it. We have to check if it needs too much of a hack to run `jekyll-scholar` with `gh-pages`. On the other hand, while `bibbase` is fine for a bibliographic list (like the one on the website), I don't see any way how to use it with inline bibliographic references in the guidelines.

**Comment by rettinghaus** [comment]
@musicEnfanthen any progress with this?

**Comment by lpugin** [comment]
gh-pages does not allow to run plugins, so for this to work you would need to build the pages outside gh-pages and then push the result to the repo. We need to make sure this is not an overkill.

**Comment by musicEnfanthen** [comment]
I've experimented with it a while ago, but did not get very far. My impression was the same as @lpugin 's . Building and repushing the pages externally seems to be quite an overkill, especially when this has to be done for multiple repos (at least guidelines and website).

Still would be great to have a solution for this.
