### ISSUE TITLE
Removing remaining html in the xsl output

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#6]

**Comment by kepper** [comment]
@lpugin, what HTML is still remaining? `<img>` has been dealt with, already, and I'm not aware of other html-related problems (incorrectly closing tags) right now

**Comment by lpugin** [comment]
There are some links remaining - see line 25 in https://github.com/music-encoding/guidelines/blob/master/_guidelines-v3/21-text/01-textDivisions.md

**Comment by kepper** [comment]
the problem seems to be solved already, probably closed by a6b5046e4089c01829417dfec28015325626b5df
