### ISSUE TITLE
classBox missing borders

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#66]
The `classBox` in data-types has no borders on the right and at the bottom. 
Is this intentional, or missing in CSS?

**Comment by kepper** [comment]
intentional. I wouldn't do one on the right, because they nest quite deeply, and an additional margin / padding on the right would double the problems on mobile devices, but I'm feeling less strong about the bottom one. It just fills up even more space, with almost no additional information…

**Comment by ahankinson** [comment]
It does look weird.

**Comment by bwbohl** [comment]
yes indeed and the rendition is different depending on the browser you use. We should either hide or show ALL borders.
