### ISSUE TITLE
Add anchors to specific attributes in elements

### ISSUE THREAD

**Issue by ahankinson** [music-encoding/guidelines#67]
For example, it would be nice to link to the `@enclose` attribute on `<accid>`. There are likely two parts to this -- 1: including an `id` on the HTML element (`id="accid-att-enclose"`) and 2: Adding a small `<a href="#accid-att-enclose">(some fancy icon symbol here)</a>` to let people access the link.

**Comment by musicEnfanthen** [comment]
@ahankinson Could you give a short feedback if this is still needed? If so, could you please clarify a bit. I am having trouble to understand where the anchors should be added and where the links should go.

**Comment by rettinghaus** [comment]
ping @ahankinson

**Comment by rettinghaus** [comment]
I played around with the xslt for generating the pages. We could add id attributes to the attributes, but we cannot link to them, because we have the different tabs for attributes, which prevent jumping to the linked element.
