### ISSUE TITLE
Adding some link templates

### ISSUE THREAD

**Issue by lpugin** [music-encoding/guidelines#7]
We can see if we want to have specific templates for links with CSS to make them simpler to edit

**Comment by lpugin** [comment]
@kepper  change links to elements to
```
{% include link elem="mei" %}
```

**Comment by lpugin** [comment]
@kepper change links to sections with
```
See section {% include link id="shared" %}.
See section {% include link id="headerIndependentHeader" %}.
```
The link-section template will look for the section name to be used for the link text and produce
```
See section <a href="/v3/guidelines/shared.html">Shared Elements, Models, and Attributes</a>.
See section <a href="/v3/guidelines/header.html#headerIndependentHeader">Independent Headers</a>.
```
respectively.

As it is now no section number is added to the link text but this can be added later on if necessary

**Comment by bwbohl** [comment]
what about the link_ptr change @lpugin proposed in #9 should I implement it?

**Comment by lpugin** [comment]
Isn't this? I already added the `link` template. (I probably thought that `link` was compacter than `link_ptr`.)

**Comment by bwbohl** [comment]
link is there
