### ISSUE TITLE
Revise 01: Introduction to MEI

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#80]
This issue can be used to discuss chapter 1 of the guidelines.

**Comment by bwbohl** [comment]
I guess this can be closed?

**Comment by bwbohl** [comment]
> I guess this can be closed?

Spotted something that maybe should be a bit more elaborate ;-)
I could imagine to describe this differentiation in chapter 2, though ( #81 )

**Comment by kepper** [comment]
this can be closed
