### ISSUE TITLE
Revise 07: Repertoire: String Tablature

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#86]
This issue can be used to discuss chapter 7 of the guidelines.

**Comment by kepper** [comment]
There is something coming up from @DILewis and @reinierdevalk in connection with #MEC2020, but as this includes new markup proposals, it's probably better handled in the dev version. Leaving it as is for now…

**Comment by musicEnfanthen** [comment]
This will be solved by music-encoding/music-encoding#1468
