### ISSUE TITLE
Revise 08: Lyrics and Performance Directions

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#87]
This issue can be used to discuss chapter 8 of the guidelines.

**Comment by ndubo** [comment]
I'm working on the revision of the guidelines chapter 8.1. How do I get to the embedded xml-examples?

**Comment by lpugin** [comment]
The one in this section https://github.com/music-encoding/guidelines/tree/master/_includes/v4/examples/shared is in this folder 
https://github.com/music-encoding/guidelines/tree/master/_includes/v4/examples/shared
namely: https://github.com/music-encoding/guidelines/blob/master/_includes/v4/examples/shared/shared-sample010.xml

**Comment by ndubo** [comment]
Found it. Thanks!

**Comment by kepper** [comment]
There is great overlap between chapters 3, 8 and 9. What follows is a proposal on how to structure chapter 8 (Lyrics) which seeks to deduplicate information between all three of them, and tries to propose a comprehensible order. Most notably, this tries to move performed text to 8, and everything else to 9. See also https://github.com/music-encoding/guidelines/issues/82#issuecomment-621469130

- Intro (f necessary)
- Lyric Syllables (was: _8.2.1_)
- Vocally performed text within notes (was: _8.2.2_)
- Vocally performed text encoded separately (was: _8.2.3_)

**Drama** and **stage directions** are completely lacking so far…
**Fingering** (currently lacking, but listed as _8.4_) should move to either Shared or CMN

**Comment by rettinghaus** [comment]
@kepper I'll add a bit about fingering in CMN.

**Comment by th-we** [comment]
Fingering is an interesting topic that might be sensible to discuss more in depth.  I just looked through guitar notation, which has multiple categories of fingerings:

* left hand
* right hand
* fret/position number
* string number
* barré indication

And for each category (except for left hand fingerings, as far as I'm aware), there is a multitude of historic and contemporary possible visual representations for the same semantic thing.  There should be some best practice description for classifying fingerings, describing their logical meaning and their visual representation.  But maybe that's too much to lay out in the guidelines, maybe that's something for the schema.

Any other instruments that would be interesting to look at?  Brass, trombone, organ footings, percussion/mallets?  (Woodwind diagrams are particularly challenging, better not open that can of worms right now.)

**Comment by rettinghaus** [comment]
@th-we I wonder, if [`att.stringtab`](https://music-encoding.org/guidelines/v4/attribute-classes/att.stringtab.html) is visual and to be used in non-tablatur notation. Would you open a new issue on `fingering` for the schema?
