### ISSUE TITLE
Revise 09: Text Encoding

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#88]
This issue can be used to discuss chapter 9 of the guidelines.

**Comment by margrethesb** [comment]
Faulty link, 9.1.1.

{% include desc atts="div/type" %}

**Comment by margrethesb** [comment]
9.1.1. Check this.

Having said that div identifies any structural organization of text, it is often helpful to distinguish the typology of division. The attributes @type and @subtype can be used for this purpose. It is required that @type be present when @subtype is used, though their values can be freely set by the encoder.

The following example shows the use of @type to indicate three prefaces in English, German and Italian are columns on the same page.

<front>
   <div n="1" type="column" xml:lang="en">
      <head>
         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>Preface
      </head>
      
   </div>
   <div n="2" type="column" xml:lang="de">
      <head>Vorwort</head>
      
   </div>
   <div n="3" type="column" xml:lang="it">
      <head>Prefazione</head>
      
   </div>
   <pb></pb>
</front>

**Comment by margrethesb** [comment]
9.1.3. Faulty link:


{% include desc atts="list/type" %}

**Comment by margrethesb** [comment]
9.1.3. Check this re: @type

<list>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>Ornaments in different languages
   </head>
   <li n="English" xml:lang="en">Turn</li>
   <li n="Italian" xml:lang="it">Gruppetto</li>
   <li n="French" xml:lang="fr">Gruppetto</li>
   <li n="German" xml:lang="de">Doppelschlag</li>
</list>

**Comment by margrethesb** [comment]
9.1.3. @type faulty

**Comment by margrethesb** [comment]
9.1.5. Same

**Comment by margrethesb** [comment]
And 9.1.6., 9.1.7., 9.3.1., 9.3.2.2., 9.3.2.4.

**Comment by kepper** [comment]
There is great overlap between chapters 3, 8 and 9. What follows is a proposal on how to structure chapter 9 (Text) which seeks to deduplicate information between all three of them, and tries to propose a comprehensible order. Most notably, this tries to move performed text to 8, and everything else to 9. See also https://github.com/music-encoding/guidelines/issues/82#issuecomment-621469130 and https://github.com/music-encoding/guidelines/issues/87#issuecomment-621469442

- Intro (if necessary)
- Encoding Text Features
  - Paragraphs (was: _8.1.1_, _9.1.2_)
  - Text Rendition (was: _8.1.2_)
  - Figures (was: _9.2.1_)
  - Lists (was: _9.1.3_)
  - Tables (was: _9.2.2_)
  - Quotation (was: _9.1.4_)
  - Poetry (was: _9.1.5_, _8.2.3_, could also be moved to 9 instead)
  - Names (was: _8.1.4_, _9.3.1_, _9.3.2_)
  - Dates (ditto)
  - Bibliographic References (was: _8.1.6_, _8.1.7_, needs to cover biblStruct as well)
  - Footnotes and other Annotations (was: _8.1.5_, should also be referenced in editTrans chapter)
- Text Document Structures
  - Divisions (was: _9.1.1_)
  - FrontMatter / BackMatter (was: _9.1.6_, _9.1.7_)
