### ISSUE TITLE
Revise 11: Scholarly Editing with MEI

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#90]
This issue can be used to discuss chapter 11 of the guidelines.

**Comment by Grabitz** [comment]
I spotted the following inconsistencies:
- 11.2. model.model.choicePart in Guidelines but model.choicePart in specs
- 11.2.1.1. I wasn't able to find @extsym in specs
- 11.2.4.1 I wasn't able to find <gap> @quantity in specs
