### ISSUE TITLE
Revise 13: Linking Data

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#92]
This issue can be used to discuss chapter 13 of the guidelines.

**Comment by musicEnfanthen** [comment]
The linking data chapter has the following inconsistencies in regard to MEI v4:

- `xlink:title` is not in the specs
- the whole `linkAlign` module is not available anymore (`timeline` element is deprecated, see cf13ae3. `when` attribute is still available but for `recording` and `clip` that are documented in chapter [12.2. Performances](https://music-encoding.org/guidelines/v4/content/facsimilesrecordings.html#performances)), see also discussion in #20 

If there is no objection, I will remove the whole section on [Linking and Alignment](https://music-encoding.org/guidelines/v4/content/linkingdata.html#linkAlign) and the xlink:title in the first part of the chapter. Also do some clean up of the first part.

**Comment by musicEnfanthen** [comment]
@kepper @pe-ro Is it correct that there is no `xlink:title` attribute in the specs? Do not find it in v4 nor in v3. Is this a "relict" from v2?

**Comment by kepper** [comment]
Yes, `@xlink:title` was documented in v2… The stuff from LinkAlign was partially moved (`<when>` is now in MEI.performance), and partically omitted (`<timeline>` is gone, as it seemeed redundant). Hope this helps…

**Comment by musicEnfanthen** [comment]
Thanks for the clarification. So I would remove the whole LinkAlign part of the current chapter and replace it with a placeholder for Linked Data approaches. @musicog and me will have another look on it next week.

**Comment by kepper** [comment]
Yes. And I must not forget to cover `<when>` in chapter 12 (#91)…

**Comment by musicEnfanthen** [comment]
Ok, good.

Another question: The attributes from `att.linking` are now also available in `<ptr`> and `<ref>`. We will definitely mention them in chapter 13, but are not sure about giving an detailed explanation here. 

One reason: There is already a description and elaboration in chapter 10 (analysis): [General Relationships between Elements](https://music-encoding.org/guidelines/v4/content/analysisharm.html#analysisDescribingRelationships). I would like to link there from the Linking chapter, but have the strong feeling that in general the chapter "Analysis" is the wrong place for the explanation of `att.linking` attributes. Shouldn't it be in the `Shared` chapter (02) as a shared concept? Then we could link to chapter 2 from 10-Analysis and from 13-Linking chapters (and others as well where needed, Scholarly Markup?)

**Comment by kepper** [comment]
Yes and no. At first sight, this sounds reasonable. But then again, analysis in MEI historically means more than musical analysis in the sense of Riemann, Schenker etc. If someone states that one element is a `@copyof` another element, that's some kind of analysis. It becomes even clearer when looking at `@corresp`, which doesn't have the side effect of (potentially) saving markup. That said, I think it's best to move _parts_ of this chapter to chapter 2 (#81), and leave others in chapter 10 (#89). There is also nothing wrong with covering a shared / generic concept from more than once, each time with a different perspective. We should just make sure that those things get linked well. For our links, it doesn't matter where a chapter is located, so if you link to a sub-chapter of 10, it can be moved to 02 without breaking the link. I won't have the time to have a closer look, but maybe you can start playing with this together with @musicog? Thanks!

**Comment by kepper** [comment]
I think this chapter is good enough to be included, or at least most of it. For now, I would just kick out 13.3 and 13.4, and merge the rest. What do you think, @musicEnfanthen?

**Comment by musicog** [comment]
I'm currently working on content for 13.3 / 13.4  -- but I appreciate this is rather late! (sorry!)
I agree that the rest of the chapter could stand alone for now. Could we merge in 13.3 / 13.4 at a later (soon) point?

**Comment by kepper** [comment]
of course – and it's great to hear you're already working on this :-) So, let's include what we have already, and take care of the rest asap…

**Comment by musicEnfanthen** [comment]
@kepper @musicog 
I think we should/could have the first two sections merged right away. Shall we remove or leave the placeholder in sections 13.3. & 13.4. for now?

**Comment by musicog** [comment]
The "(soon)" in my previous comment is doing some heavy lifting there, sorry :-(
Personally I'd remove the placeholder stubs until the content is ready (to give a more coherent read of what's there), but it's up to @kepper of course

**Comment by musicEnfanthen** [comment]
Ok, good. Will remove the whole section 13.3 for now.

**Comment by kepper** [comment]
👍

**Comment by kepper** [comment]
this has been fixed by #168
